package com.goldenpie.devs.kievrest.utils;


public enum ModelTypeEnum {
    SELECTIONS, RESTAURANTS, CLUBS, BARS, MUSEUMS, SHOPS, RECREATIONS, ATTRACTIONS, CITES, HOTELS,
    CONCERTS, EXHIBITIONS, FESTIVALS, THEATERS, YARMARKI, ENTERTAINMENT, FILMS, NEWS
}
